apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/api.update-strategy: digest
    argocd-image-updater.argoproj.io/image-list: >
      api=dfal/playground-app-web-api:latest,
      front=dfal/playground-app-web-ui:latest
    argocd-image-updater.argoproj.io/api.helm.image-name: api.image
    argocd-image-updater.argoproj.io/api.helm.image-tag: api.tag
    argocd-image-updater.argoproj.io/front.helm.image-name: front.image
    argocd-image-updater.argoproj.io/front.helm.image-tag: front.tag
  name: playground-app-staging
spec:
  destination:
    namespace: "staging"
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: staging/manifests
    repoURL: https://github.com/dfal/playground-deployment
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
