apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: playground-app-preview
spec:
  generators:
    - pullRequest:
        github:
          owner: dfal
          repo: playground-app
          tokenRef:
            key: token
            secretName: github-token
        requeueAfterSeconds: 60
  template:
    metadata:
      name: "playground-app-{{branch}}-{{number}}"
      annotations:
        argocd-image-updater.argoproj.io/write-back-method: argocd
        argocd-image-updater.argoproj.io/api.update-strategy: name
        argocd-image-updater.argoproj.io/image-list: "api=hub.docker.com/dfal/playground-app-web-api,front=hub.docker.com/dfal/playground-app-web-ui"
        argocd-image-updater.argoproj.io/api.allow-tags: "regexp:^({{branch}}|latest)$"
    spec:
      destination:
        namespace: "pr-{{branch}}"
        server: "https://kubernetes.default.svc"
      project: default
      syncPolicy:
        automated: {}
      source:
        path: pr-envs
        repoURL: https://github.com/dfal/playground-deployment
        targetRevision: HEAD
        helm:
          parameters:
            - name: namespace
              value: "pr-{{branch}}"
            - name: version
              value: "{{branch}}"
