apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: playground-app-preview
spec:
  generators:
    - pullRequest:
        github:
          owner: dfal
          repo: playground-app
          tokenRef:
            key: token
            secretName: github-token
        requeueAfterSeconds: 60
  template:
    metadata:
      annotations:
        argocd-image-updater.argoproj.io/write-back-method: argocd
        argocd-image-updater.argoproj.io/image-list: >
          api=dfal/playground-app-web-api:{{branch}},
          front=dfal/playground-app-web-ui:{{branch}}
        argocd-image-updater.argoproj.io/api.update-strategy: digest
        argocd-image-updater.argoproj.io/front.update-strategy: digest
        argocd-image-updater.argoproj.io/api.helm.image-name: api.image
        argocd-image-updater.argoproj.io/api.helm.image-tag: api.tag
        argocd-image-updater.argoproj.io/front.helm.image-name: front.image
        argocd-image-updater.argoproj.io/front.helm.image-tag: front.tag
      name: "playground-app-{{branch}}-{{number}}"
    spec:
      destination:
        namespace: "pr-{{branch}}"
        server: "https://kubernetes.default.svc"
      project: default
      syncPolicy:
        automated:
          selfHeal: false
      source:
        path: pr-envs
        repoURL: https://github.com/dfal/playground-deployment
        targetRevision: HEAD
        helm:
          parameters:
            - name: image
              value: api.image
            - name: tag
              value: api.tag
            - name: namespace
              value: "pr-{{branch}}"
            - name: version
              value: "{{branch}}"
