apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: playground-app-preview
spec:
  generators:
    pullRequest:
      github:
        owner: dfal
        repo: playground-app
        tokenRef:
          key: token
          secretName: github-token
      requeueAfterSeconds: 60
  template:
    metadata:
      name: 'playground-app-{{branch}}-{{number}}'
    spec:
      destination:
        namespace: 'pr-{{branch}}'
        server: 'https://kubernetes.default.svc'
      project: default
      source:
        path: pr-envs/
        repoURL: https://github.com/dfal/playground-deployment
        targetRevision: HEAD
        helm:
          parameters:
            - name: namespace
              value: 'pr-{{branch}}'
            - name: version
              value: '{{branch}}'
