---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-app-rules
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: external-nginx
  rules:
    - host:
      http:
        paths:
          - path: /{{ .Values.namespace }}/api
            pathType: Prefix
            backend:
              service:
                name: web-api-service
                port:
                  number: 9000
          - path: /{{ .Values.namespace }}
            pathType: Prefix
            backend:
              service:
                name: web-ui-service
                port:
                  number: 80
