apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-api
  template:
    metadata:
      labels:
        app: web-api
    spec:
      containers:
      - name: playground-app-web-api
        image: dfal/playground-app-web-api:{{ .Values.version }}
        env:
        - name: PORT
          value: "9000"
        - name: OPENWEATHERMAP_API_KEY
          value: {{ .Values.openweathermap_api_key }}
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
          ports:
          - containerPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: web-api-service
spec:
  type: ClusterIP
  selector:
    app: web-api
  ports:
  - port: 9000
    name: http-port